// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use the DIRECT connection (Supabase pgBouncer can't migrate);
    // falls back to DATABASE_URL for local/non-pooled setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
